import { useEffect, useState } from 'react'
import { useServerFn } from '@tanstack/react-start'
import { addCurrentListingSharedDecisionNote, getListingDecisionHistory, saveCurrentListingDecision } from './listing-decisions.functions'
import { legacyDecisionStateLabels, type listingDecisionStateSchema } from './listing-decisions.schemas'
import type { z } from 'zod'

type DecisionState = z.infer<typeof listingDecisionStateSchema>
type Decision = { state: DecisionState; note: string; expectedQuantity: number | null }
type History = Awaited<ReturnType<typeof getListingDecisionHistory>>
const stateLabels: Record<DecisionState, string> = { interesting: 'Interesting', watch: 'Watch', ignore: 'Ignore', buy: 'Buy', archived: 'Archived', ...legacyDecisionStateLabels }

function DecisionHistory({ listingId, refreshKey }: { listingId: string; refreshKey: number }) {
  const load = useServerFn(getListingDecisionHistory); const addNote = useServerFn(addCurrentListingSharedDecisionNote)
  const [history, setHistory] = useState<History>([]); const [body, setBody] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  useEffect(() => { let live = true; void load({ data: { listingId } }).then((items) => { if (live) setHistory(items) }).catch(() => { if (live) setError('Could not load shared history.') }); return () => { live = false } }, [listingId, refreshKey, load])
  async function submit() { if (!body.trim()) return; setBusy(true); setError(''); try { await addNote({ data: { listingId, body } }); setBody(''); setHistory(await load({ data: { listingId } })) } catch { setError('Could not add shared note.') } finally { setBusy(false) } }
  return <section className="mt-3 border-t border-border pt-3" aria-label="Decision history"><h2 className="text-sm font-medium">Shared decision history</h2><div className="mt-2 space-y-2 text-xs">{history.length ? history.map((item) => <article key={item.id} className="rounded border border-border px-2 py-1.5"><p><span className="font-medium">{item.authorName}</span>{item.kind === 'state' ? <> changed {item.fromState ? stateLabels[item.fromState as DecisionState] : 'no prior state'} to {stateLabels[item.toState as DecisionState]}</> : <> shared a note</>}</p>{item.kind === 'note' ? <p className="mt-1 whitespace-pre-wrap text-muted-foreground">{item.body}</p> : null}<time className="mt-1 block text-muted-foreground" dateTime={item.createdAt.toISOString()}>{item.createdAt.toLocaleString()}</time></article>) : <p className="text-muted-foreground">No shared decisions or notes yet.</p>}</div><div className="mt-2 flex gap-2"><textarea className="min-h-14 flex-1 rounded border border-border bg-background p-2 text-xs" maxLength={2_000} placeholder="Add a shared note" value={body} onChange={(event) => setBody(event.target.value)} /><button className="self-end rounded bg-primary px-2 py-1 text-xs text-primary-foreground disabled:opacity-50" disabled={busy || !body.trim()} onClick={() => void submit()} type="button">{busy ? 'Adding…' : 'Share note'}</button></div>{error ? <p role="alert" className="mt-1 text-xs text-destructive">{error}</p> : null}</section>
}

export function ListingDecisionControl({ listingId, initial }: { listingId: string; initial: Decision }) {
  const [value, setValue] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [refreshKey, setRefreshKey] = useState(0); const save = useServerFn(saveCurrentListingDecision)
  useEffect(() => { setValue(initial); setError('') }, [listingId, initial])
  async function submit() { setBusy(true); setError(''); try { setValue(await save({ data: { listingId, ...value, state: value.state as Extract<DecisionState, 'interesting' | 'watch' | 'ignore' | 'buy' | 'archived'> } })); setRefreshKey((key) => key + 1) } catch { setError('Could not save review decision.') } finally { setBusy(false) } }
  const isLegacy = value.state in legacyDecisionStateLabels
  return <section className="mt-4 border-y border-border py-3 text-xs" aria-label="Review decision"><div className="flex flex-wrap items-center gap-2"><strong>Decision</strong><select value={value.state} onChange={(event) => setValue({ ...value, state: event.target.value as DecisionState })} className="rounded border border-border bg-background px-2 py-1">{isLegacy ? <option value={value.state}>{stateLabels[value.state]}</option> : null}<option value="interesting">Interesting</option><option value="watch">Watch</option><option value="ignore">Ignore</option><option value="buy">Buy</option><option value="archived">Archived</option></select><label>Expected qty <input className="ml-1 w-16 rounded border border-border bg-background px-1 py-1" type="number" min="1" value={value.expectedQuantity ?? ''} onChange={(event) => setValue({ ...value, expectedQuantity: event.target.value ? Number(event.target.value) : null })} /></label><button className="rounded bg-primary px-2 py-1 text-primary-foreground disabled:opacity-50" disabled={busy} onClick={() => void submit()} type="button">{busy ? 'Saving…' : 'Save'}</button></div>{isLegacy ? <p className="mt-2 text-muted-foreground">This is a preserved legacy decision. Choose a current state to transition it.</p> : null}{error ? <p role="alert" className="mt-1 text-destructive">{error}</p> : null}<textarea className="mt-2 w-full rounded border border-border bg-background p-2" rows={2} maxLength={500} placeholder="Private review note" value={value.note} onChange={(event) => setValue({ ...value, note: event.target.value })} /><DecisionHistory listingId={listingId} refreshKey={refreshKey} /></section>
}
