import { createFileRoute, Link, redirect } from '@tanstack/react-router'
import { getPublicSession } from '~/features/auth/auth.functions'
import { getListingDetail } from '~/features/catalog/listing-detail.functions'
import type { ListingDetail } from '~/features/catalog/listing-detail.schemas'

export const Route = createFileRoute('/listings/$listingId')({
  beforeLoad: async () => { if (!(await getPublicSession())) throw redirect({ to: '/login' }) },
  loader: ({ params }) => getListingDetail({ data: { listingId: params.listingId } }),
  head: () => ({ meta: [{ title: 'Listing detail · Hoardcore' }] }),
  component: ListingDetailPage,
})

function Field({ label, value }: { label: string; value: string }) { return <div><dt className="text-muted-foreground">{label}</dt><dd className="mt-1 break-all font-medium text-foreground">{value}</dd></div> }
function Observation({ observation }: { observation: ListingDetail['observations'][number] }) { return <article className="rounded-lg border border-border bg-card p-5"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-medium text-foreground">{observation.title}</h3><time dateTime={observation.observedAt.toISOString()} className="text-sm text-muted-foreground">{observation.observedAt.toLocaleString()}</time></div><p className="mt-2 text-sm text-muted-foreground">{observation.price ? `${observation.currency ?? ''} ${observation.price}`.trim() : 'No price'} · {observation.available ? 'Available' : 'Unavailable'}</p>{observation.evidence ? <details className="mt-4 rounded-md border border-border"><summary className="cursor-pointer px-3 py-2 text-sm text-muted-foreground">Captured evidence ({observation.evidence.contentType ?? 'unknown type'})</summary><div className="border-t border-border p-3"><p className="text-xs text-muted-foreground">Evidence {observation.evidence.id}{observation.evidence.run ? ` · run ${observation.evidence.run.id} · ${observation.evidence.run.status}` : ''}</p><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap break-words rounded bg-muted p-3 text-xs text-foreground">{observation.evidence.payload}</pre></div></details> : <p className="mt-4 text-xs text-muted-foreground">No retained evidence attached.</p>}</article> }

function ListingDetailPage() {
  const detail = Route.useLoaderData() as ListingDetail | null
  if (!detail) return <main className="mx-auto max-w-3xl px-4 py-16 text-center" id="main-content"><h1 className="text-2xl font-semibold text-foreground">Listing not found</h1><p className="mt-2 text-muted-foreground">This listing may not have current normalized state yet.</p><Link className="mt-5 inline-block text-primary underline" to="/listings">Return to listings</Link></main>
  return <main className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-6 sm:py-10" id="main-content"><Link to="/listings" className="text-sm text-primary underline">← Back to listings</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-primary">Listing detail</p><h1 className="mt-1 text-3xl font-semibold text-foreground">{detail.current.title}</h1><p className="mt-2 text-muted-foreground">{detail.source.displayName} · {detail.source.moduleId}</p></div><a href={detail.url} target="_blank" rel="noreferrer" className="text-sm text-primary underline">Open source listing ↗</a></div><section className="mt-8 grid gap-5 lg:grid-cols-2" aria-label="Current normalized state"><div className="rounded-lg border border-border bg-card p-5"><h2 className="text-lg font-semibold text-foreground">Current normalized state</h2><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><Field label="Product" value={detail.product.title} /><Field label="Variant" value={detail.variant.title ?? '—'} /><Field label="Price" value={detail.current.price ? `${detail.current.currency ?? ''} ${detail.current.price}`.trim() : '—'} /><Field label="Availability" value={detail.current.available ? 'Available' : 'Unavailable'} /><Field label="SKU" value={detail.variant.sku ?? '—'} /><Field label="Last observed" value={detail.current.observedAt.toLocaleString()} /></dl>{detail.product.description ? <p className="mt-5 border-t border-border pt-4 text-sm leading-6 text-muted-foreground">{detail.product.description}</p> : null}</div><div className="rounded-lg border border-border bg-card p-5"><h2 className="text-lg font-semibold text-foreground">Identity</h2><dl className="mt-4 space-y-3 text-sm"><Field label="Product ID" value={detail.product.id} /><Field label="Variant ID" value={detail.variant.id} /><Field label="Listing ID" value={detail.id} /></dl></div></section><section className="mt-8" aria-label="Listing observations and evidence"><h2 className="text-xl font-semibold text-foreground">Observation history</h2><p className="mt-1 text-sm text-muted-foreground">Timestamped observations are retained separately from the current state.</p>{detail.observations.length === 0 ? <p className="mt-4 rounded-lg border border-dashed border-border p-8 text-center text-muted-foreground">No observations recorded yet.</p> : <div className="mt-4 space-y-4">{detail.observations.map((observation) => <Observation key={observation.id} observation={observation} />)}</div>}</section></main>
}
